site_name: My DevOps Notes
site_description: Personal DevOps and Kubernetes notes
site_url: https://bhaskar0545.github.io/devopsnotes/
repo_url: https://github.com/bhaskar0545/devopsnotes
repo_name: bhaskar0545/devopsnotes

theme:
  name: mkdocs
  navigation_depth: 3
  collapse_navigation: false
  sticky_navigation: true
  titles_only: false
  prev_next_buttons_location: bottom
  
nav:
  - Home: index.md
  - ML Ops:
      - Refs: MLOps/Refs.md
  - Kubernetes:
      - Concepts: kubernetes/concepts.md
      - Pods: kubernetes/pods.md
      - Services: kubernetes/services.md
      - Deployments: kubernetes/deployments.md
      - Troubleshooting: troubleshooting.md
      - Cheatsheet: cheatsheets.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - fenced_code
  - toc:
      permalink: true

extra_css:
  - css/extra.css
