site_name: My DevOps Notes
site_url: https://bhaskar0545.github.io/devopsnotes/

theme:
  name: cinder
  colorscheme: atom-one-light
  hljs_languages:
    - yaml
    - bash
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Kubernetes:
      - Concepts: kubernetes/concepts.md
      - Pods: kubernetes/pods.md
      - Services: kubernetes/services.md
      - Deployments: kubernetes/deployments.md
  - Cheatsheets: cheatsheets.md
  - Troubleshooting: troubleshooting.md
